export enum MYSQL {
  HOST = 'MYSQL_HOST',
  PORT = 'MYSQL_PORT',
  USERNAME = 'MYSQL_USERNAME',
  PASSWORD = 'MYSQL_PASSWORD',
  TYPE = 'MYSQL_TYPE',
  DATABASE = 'MYSQL_DATABASE',
}

export enum ENV_JWT {
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRED = 'JWT_EXPIRED',
  JWT_EXPIRED_REFRESH = 'JWT_EXPIRED_REFRESH',
}
